services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${{ secrets.LR_DB_ROOT_PASS }}
      MARIADB_DATABASE: ${{ secrets.LR_DB_NAME }}
      MARIADB_USER: ${{ secrets.LR_DB_USER }}
      MARIADB_PASSWORD: ${{ secrets.LR_DB_PASS }}
    ports:
      - ${{ secrets.LR_DB_PORT }}:${{ secrets.LR_DB_DCKR_PORT }}