name: API Gateway CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apigateway

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.16.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: "npm"
          cache-dependency-path: apigateway/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      # - name: Run tests
      #   run: npm test
